name: omega_view_smart_plan_320
description: Ваше описание

# Версия Flutter SDK
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  uuid: ^4.0.0 
  equatable: ^2.0.3
  path_provider: ^2.1.3 
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Генерация адаптеров Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9 
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
